### ISSUE TITLE
Distinguish b/w syntax and style

### ISSUE THREAD

**Issue by otoomet** [info201/book#18]
I think we should keep syntax and style clearly apart, and add a paragraph or so about the style

  * 5.3 (comments) currently states that "We put descriptive comments immediately above the code it describes, but you can also put very short notes at the end of the line of code (preferably following two spaces)".  This is a style suggestion, not syntactic requirement, and should be clearly stated as such.

  * Emacs/ESS aligns comments differently depending on how many #-s it has (# -- around col 40, ## - current indent, ### - col 1).  So there are more ways to define a good style for comments.

  * should add a few words about variable naming (varName, VarName, var.name, var_name are all widely used), perhaps mention the S3 classes and dot issue. 

Perhaps to add a paragraph or like that about style after most of the relevant syntactic requirements are described?

**Comment by mkfreeman** [comment]
Switched to tidyverse style guide, and added this paragraph:

> Note: There is an important distinction between syntax and style. You need to use the proper syntax such that your machine understands your code. This requires that you follow a set of rigid rules for what code can be procesed. Style is what helps make your code understandable for other humans. Good style is not required to get your code to run, but it’s imperative for writing clear, (human) readable code.
