### ISSUE TITLE
Order of sections in Chapter 7

### ISSUE THREAD

**Issue by zmbc** [info201/book#25]
Chapter 7 was a bit jarring to read for me because I felt like I had missed something.

Section 7.2.1 starts:

> Remember that in R, everything is a vector.

But it's not until section 7.5.2 that this is stated.

The last example in section 7.3 uses knowledge of boolean vector filtering and recycling, but those concepts aren't introduced until 7.4 and 7.5.1 respectively.

In general I think it's fine to use concepts a little before the reader understands them rigorously, but the specific way it was worded in this chapter (e.g. the word "remember") may make the reader think they are missing required background knowledge that won't be covered in the book.

**Comment by otoomet** [comment]
I re-wrote a re-structured the section quite a bit, closing it now.

Feel free to open a new one if you are unhappy with the results!
